/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pharmeny;

import java.awt.Dimension;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Medicine_Details extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Medicine_Details.class.getName());
    private Connection conn;
    private DefaultTableModel model;

    /**
     * Creates new form Medicine_Management
     */
    public Medicine_Details() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        conn = JDBC.getConnection();
        loadTableData();
        addActionListeners();
        jScrollPane1.setVerticalScrollBarPolicy(
        javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        med_id = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        cat = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        qty = new javax.swing.JLabel();
        expiry = new javax.swing.JLabel();
        supplier = new javax.swing.JLabel();
        id_out = new javax.swing.JTextField();
        name_out = new javax.swing.JTextField();
        cat_out = new javax.swing.JTextField();
        price_out = new javax.swing.JTextField();
        qty_out = new javax.swing.JTextField();
        expiry_out = new javax.swing.JTextField();
        supplier_out = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        update = new javax.swing.JButton();
        del = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        refresh = new javax.swing.JButton();
        search = new javax.swing.JLabel();
        search_out = new javax.swing.JTextField();
        Search = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medicine Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        med_id.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        med_id.setText("Medicine ID:*");

        name.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        name.setText("Name:*");

        cat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cat.setText("Category:");

        price.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        price.setText("Price:*");

        qty.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        qty.setText("Quantity:*");

        expiry.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        expiry.setText("Expiry Date (YYYY-MM-DD):*");

        supplier.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        supplier.setText("Supplier:*");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(med_id)
                    .addComponent(name)
                    .addComponent(cat)
                    .addComponent(price)
                    .addComponent(qty)
                    .addComponent(expiry)
                    .addComponent(supplier))
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(id_out)
                    .addComponent(name_out)
                    .addComponent(cat_out)
                    .addComponent(price_out)
                    .addComponent(qty_out)
                    .addComponent(expiry_out)
                    .addComponent(supplier_out))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(med_id)
                    .addComponent(id_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(name_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cat)
                    .addComponent(cat_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(price)
                    .addComponent(price_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qty)
                    .addComponent(qty_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(expiry)
                    .addComponent(expiry_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(supplier)
                    .addComponent(supplier_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Actions", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        add.setBackground(new java.awt.Color(0, 255, 0));
        add.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        add.setForeground(new java.awt.Color(255, 255, 255));
        add.setText("Add");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        update.setBackground(new java.awt.Color(51, 153, 255));
        update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        del.setBackground(new java.awt.Color(255, 51, 51));
        del.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        del.setForeground(new java.awt.Color(255, 255, 255));
        del.setText("Delete");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        clear.setBackground(new java.awt.Color(153, 153, 153));
        clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 255, 255));
        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(153, 0, 153));
        refresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refresh.setForeground(new java.awt.Color(255, 255, 255));
        refresh.setText("Refresh");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(add)
                .addGap(18, 18, 18)
                .addComponent(update)
                .addGap(18, 18, 18)
                .addComponent(del)
                .addGap(18, 18, 18)
                .addComponent(clear)
                .addGap(18, 18, 18)
                .addComponent(refresh)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add)
                    .addComponent(update)
                    .addComponent(del)
                    .addComponent(clear)
                    .addComponent(refresh))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search.setText("Search:");

        Search.setBackground(new java.awt.Color(255, 153, 0));
        Search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Search.setText("Search");
        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Medicine List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price", "Quantity", "Expiry Date", "Supplier", "Status"
            }
        ));
        jTable1.setAutoscrolls(false);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 130, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(search)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(search_out, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Search)
                        .addGap(0, 149, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search)
                    .addComponent(search_out, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Search))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
        String keyword = search_out.getText().trim();
        
        try {
            model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0);
            
            String query = "SELECT * FROM medicines WHERE name LIKE ? OR category LIKE ? OR supplier LIKE ?";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.setString(1, "%" + keyword + "%");
            pst.setString(2, "%" + keyword + "%");
            pst.setString(3, "%" + keyword + "%");
            
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("medicine_id"),
                    rs.getString("name"),
                    rs.getString("category"),
                    rs.getDouble("price"),
                    rs.getInt("quantity"),
                    rs.getDate("expiry_date"),
                    rs.getString("supplier"),
                    rs.getString("status")
                });
            }
            
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No medicines found!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error searching: " + e.getMessage());
        }
    }//GEN-LAST:event_SearchActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        if (!validateInputs()) return;
        
        try {
            String query = "INSERT INTO medicines (name, category, price, quantity, expiry_date, supplier) VALUES (?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(query);
            
            pst.setString(1, name_out.getText());
            pst.setString(2, cat_out.getText());
            pst.setDouble(3, Double.parseDouble(price_out.getText()));
            pst.setInt(4, Integer.parseInt(qty_out.getText()));
            pst.setDate(5, Date.valueOf(expiry_out.getText()));
            pst.setString(6, supplier_out.getText());
            
            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Medicine added successfully!");
                clearForm();
                loadTableData();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error adding medicine: " + e.getMessage());
        }
    }//GEN-LAST:event_addActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        if (id_out.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a medicine to update first!");
            return;
        }
        
        if (!validateInputs()) return;
        
        try {
            String query = "UPDATE medicines SET name=?, category=?, price=?, quantity=?, expiry_date=?, supplier=? WHERE medicine_id=?";
            PreparedStatement pst = conn.prepareStatement(query);
            
            pst.setString(1, name_out.getText());
            pst.setString(2, cat_out.getText());
            pst.setDouble(3, Double.parseDouble(price_out.getText()));
            pst.setInt(4, Integer.parseInt(qty_out.getText()));
            pst.setDate(5, Date.valueOf(expiry_out.getText()));
            pst.setString(6, supplier_out.getText());
            pst.setInt(7, Integer.parseInt(id_out.getText()));
            
            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Medicine updated successfully!");
                loadTableData();
            }
            } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error updating medicine: " + e.getMessage());
        }
    }//GEN-LAST:event_updateActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
        if (id_out.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Select a medicine to delete first!");
            return;
        }
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Are you sure you want to delete this medicine?", 
            "Confirm Delete", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                String query = "DELETE FROM medicines WHERE medicine_id=?";
                PreparedStatement pst = conn.prepareStatement(query);
                pst.setInt(1, Integer.parseInt(id_out.getText()));
                
                 int rows = pst.executeUpdate();
                if (rows > 0) {
                    JOptionPane.showMessageDialog(this, "Medicine deleted successfully!");
                    clearForm();
                    loadTableData();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error deleting medicine: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_delActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        id_out.setText("");
        name_out.setText("");
        cat_out.setText("");
        price_out.setText("");
        qty_out.setText("");
        expiry_out.setText("");
        supplier_out.setText("");
        search_out.setText("");
        jTable1.clearSelection();
    }//GEN-LAST:event_clearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Medicine_Details().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Search;
    private javax.swing.JButton add;
    private javax.swing.JLabel cat;
    private javax.swing.JTextField cat_out;
    private javax.swing.JButton clear;
    private javax.swing.JButton del;
    private javax.swing.JLabel expiry;
    private javax.swing.JTextField expiry_out;
    private javax.swing.JTextField id_out;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel med_id;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name_out;
    private javax.swing.JLabel price;
    private javax.swing.JTextField price_out;
    private javax.swing.JLabel qty;
    private javax.swing.JTextField qty_out;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel search;
    private javax.swing.JTextField search_out;
    private javax.swing.JLabel supplier;
    private javax.swing.JTextField supplier_out;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void loadTableData() {
        try {
            model = (DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // Clear table
            
            String query = "SELECT * FROM medicines";
            PreparedStatement pst = conn.prepareStatement(query);
            ResultSet rs = pst.executeQuery();
            
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("medicine_id"),
                    rs.getString("name"),
                    rs.getString("category"),
                    rs.getDouble("price"),
                    rs.getInt("quantity"),
                    rs.getDate("expiry_date"),
                    rs.getString("supplier"),
                    rs.getString("status")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage());
        }
    }

    private void addActionListeners() {
        // Add button
        add.addActionListener(e -> addActionPerformed(e));
        
        // Update button
        update.addActionListener(e -> updateActionPerformed(e));
        
        // Delete button
        del.addActionListener(e -> delActionPerformed(e));
        
        // Clear button
        clear.addActionListener(e -> clearActionPerformed(e));
        
        // Refresh button
        refresh.addActionListener(e -> loadTableData());
        
        // Search button
        Search.addActionListener(e -> SearchActionPerformed(e));
        
        // Table selection - load data when row clicked
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                int row = jTable1.getSelectedRow();
                if (row >= 0) {
                    id_out.setText(model.getValueAt(row, 0).toString());
                    name_out.setText(model.getValueAt(row, 1).toString());
                    cat_out.setText(model.getValueAt(row, 2).toString());
                    price_out.setText(model.getValueAt(row, 3).toString());
                    qty_out.setText(model.getValueAt(row, 4).toString());
                    expiry_out.setText(model.getValueAt(row, 5).toString());
                    supplier_out.setText(model.getValueAt(row, 6).toString());
                }
            }
        });
        
    }

    

    private boolean validateInputs() {
        if (name_out.getText().trim().isEmpty() ||
            price_out.getText().trim().isEmpty() ||
            qty_out.getText().trim().isEmpty() ||
            expiry_out.getText().trim().isEmpty() ||
            supplier_out.getText().trim().isEmpty()) {
            
            JOptionPane.showMessageDialog(this, "Please fill all required fields!");
            return false;
    }
    //check numeric values
    try {
            double price = Double.parseDouble(price_out.getText());
            if (price <= 0) {
                JOptionPane.showMessageDialog(this, "Price must be greater than 0!");
                return false;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid price!");
            return false;
        }
        
        try {
            int quantity = Integer.parseInt(qty_out.getText());
            if (quantity < 0) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative!");
                return false;
                }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter valid quantity!");
            return false;
        }
        
    // Check date format
        try {
            Date.valueOf(expiry_out.getText());
        } catch (IllegalArgumentException e) {
            JOptionPane.showMessageDialog(this, "Date format must be YYYY-MM-DD");
            return false;
        }
        
        return true;
    }

    private void clearForm() {
    
    id_out.setText("");
    name_out.setText("");
    cat_out.setText("");
    price_out.setText("");
    qty_out.setText("");
    expiry_out.setText("");
    supplier_out.setText("");
    search_out.setText("");
    jTable1.clearSelection();
    
    }

}



