/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pharmeny;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author DELL
 */
public class Pharmacy_Inventory_Dashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Pharmacy_Inventory_Dashboard.class.getName());

    /**
     * Creates new form Pharmacy_Inventory_Dashboard
     */
    public Pharmacy_Inventory_Dashboard() {
        initComponents();
        setLocationRelativeTo(null);   // center screen
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topic = new javax.swing.JLabel();
        medi_mng = new javax.swing.JButton();
        sup_mng = new javax.swing.JButton();
        stock = new javax.swing.JButton();
        search = new javax.swing.JButton();
        alert = new javax.swing.JButton();
        report = new javax.swing.JButton();
        setting = new javax.swing.JButton();
        about = new javax.swing.JButton();
        logout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        topic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        topic.setForeground(new java.awt.Color(0, 102, 204));
        topic.setText("PHARMACY INVENTORY MANAGEMENT SYSTEM");

        medi_mng.setBackground(new java.awt.Color(0, 204, 0));
        medi_mng.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        medi_mng.setForeground(new java.awt.Color(255, 255, 255));
        medi_mng.setText("Medicine Details");
        medi_mng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medi_mngActionPerformed(evt);
            }
        });

        sup_mng.setBackground(new java.awt.Color(255, 102, 0));
        sup_mng.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sup_mng.setForeground(new java.awt.Color(255, 255, 255));
        sup_mng.setText("Supplier Details");
        sup_mng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sup_mngActionPerformed(evt);
            }
        });

        stock.setBackground(new java.awt.Color(51, 204, 255));
        stock.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        stock.setForeground(new java.awt.Color(255, 255, 255));
        stock.setText("View Stock");
        stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockActionPerformed(evt);
            }
        });

        search.setBackground(new java.awt.Color(153, 0, 153));
        search.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        search.setForeground(new java.awt.Color(255, 255, 255));
        search.setText("Search Medicine");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        alert.setBackground(new java.awt.Color(255, 153, 0));
        alert.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alert.setForeground(new java.awt.Color(255, 255, 255));
        alert.setText("Low Stock Alert");
        alert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertActionPerformed(evt);
            }
        });

        report.setBackground(new java.awt.Color(153, 0, 255));
        report.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        report.setForeground(new java.awt.Color(255, 255, 255));
        report.setText("Generate Reports");
        report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportActionPerformed(evt);
            }
        });

        setting.setBackground(new java.awt.Color(153, 153, 153));
        setting.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        setting.setForeground(new java.awt.Color(255, 255, 255));
        setting.setText("Settings");
        setting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingActionPerformed(evt);
            }
        });

        about.setBackground(new java.awt.Color(0, 153, 153));
        about.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setText("About");
        about.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutActionPerformed(evt);
            }
        });

        logout.setBackground(new java.awt.Color(255, 0, 51));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(118, Short.MAX_VALUE)
                .addComponent(topic)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(medi_mng, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sup_mng, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                    .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(report, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(topic)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(medi_mng, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(sup_mng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(search, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(alert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(report, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(setting, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                    .addComponent(about, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sup_mngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sup_mngActionPerformed
        // TODO add your handling code here:
        Supplier_details sd = new Supplier_details();
        sd.setLocationRelativeTo(this);
        sd.setVisible(true);
    }//GEN-LAST:event_sup_mngActionPerformed

    private void medi_mngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medi_mngActionPerformed
        // TODO add your handling code here:
        Medicine_Details md = new Medicine_Details();
        md.setLocationRelativeTo(this); // center on dashboard
        md.setVisible(true);
    }//GEN-LAST:event_medi_mngActionPerformed

    private void stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockActionPerformed
        // TODO add your handling code here:
        View_Medicine_Stock vm = new View_Medicine_Stock();
        vm.setLocationRelativeTo(this);
        vm.setVisible(true);
    }//GEN-LAST:event_stockActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        Search_Medicine sm = new Search_Medicine();
        sm.setLocationRelativeTo(this);
        sm.setVisible(true);
    }//GEN-LAST:event_searchActionPerformed

    private void alertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertActionPerformed
        // TODO add your handling code here:
        Low_Stock_Alert ls = new Low_Stock_Alert();
        ls.setLocationRelativeTo(this);
        ls.setVisible(true);
    }//GEN-LAST:event_alertActionPerformed

    private void reportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportActionPerformed
        // TODO add your handling code here:
        Generate_Reports gr = new Generate_Reports();
        gr.setLocationRelativeTo(this);
        gr.setVisible(true);
    }//GEN-LAST:event_reportActionPerformed

    private void settingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingActionPerformed
        // TODO add your handling code here:
        System_setting ss = new System_setting();
        ss.setLocationRelativeTo(this);
        ss.setVisible(true);
    }//GEN-LAST:event_settingActionPerformed

    private void aboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutActionPerformed
        // TODO add your handling code here:
        About_Pharmacy_Inventory_System ap = new About_Pharmacy_Inventory_System();
        ap.setLocationRelativeTo(this);
        ap.setVisible(true);
    }//GEN-LAST:event_aboutActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(
        this,
        "Are you sure you want to logout?",
        "Logout Confirmation",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "Logged out successfully 👋");
        new Pharmacy_Inventory_Login().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Pharmacy_Inventory_Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about;
    private javax.swing.JButton alert;
    private javax.swing.JButton logout;
    private javax.swing.JButton medi_mng;
    private javax.swing.JButton report;
    private javax.swing.JButton search;
    private javax.swing.JButton setting;
    private javax.swing.JButton stock;
    private javax.swing.JButton sup_mng;
    private javax.swing.JLabel topic;
    // End of variables declaration//GEN-END:variables
}
