/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pharmeny;

import java.sql.*;
import java.io.FileWriter;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class View_Medicine_Stock extends javax.swing.JFrame {
    private Connection conn;
    private DefaultTableModel model;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(View_Medicine_Stock.class.getName());

    /**
     * Creates new form View_Medicine_Stock
     */
    public View_Medicine_Stock() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        conn = JDBC.getConnection();
        model = (DefaultTableModel) jTable1.getModel();
        loadTableData("medicine_id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sort = new javax.swing.JLabel();
        combobox = new javax.swing.JComboBox<>();
        refresh = new javax.swing.JButton();
        export = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sort.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sort.setText("Sort by:");

        combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Name", "Category", "Price", "Quantity", "Expiry Date", "Supplier", "Total Value" }));
        combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboboxActionPerformed(evt);
            }
        });

        refresh.setBackground(new java.awt.Color(153, 204, 255));
        refresh.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        refresh.setText("Refresh");
        refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshActionPerformed(evt);
            }
        });

        export.setBackground(new java.awt.Color(153, 204, 255));
        export.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        export.setText("Export to CSV");
        export.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Category", "Price", "Quantity", "Expiry Date", "Supplier", "Total Value"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(sort)
                        .addGap(18, 18, 18)
                        .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(refresh)
                        .addGap(40, 40, 40)
                        .addComponent(export)
                        .addGap(0, 250, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sort)
                    .addComponent(combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(refresh)
                    .addComponent(export))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void refreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshActionPerformed
        // TODO add your handling code here:
        loadTableData(getSortColumn());
    }//GEN-LAST:event_refreshActionPerformed

    private void comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboboxActionPerformed
        // TODO add your handling code here:
        loadTableData(getSortColumn());
    }//GEN-LAST:event_comboboxActionPerformed

    private void exportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportActionPerformed
        // TODO add your handling code here:
        exportToCSV();
    }//GEN-LAST:event_exportActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default loosorteel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new View_Medicine_Stock().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combobox;
    private javax.swing.JButton export;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton refresh;
    private javax.swing.JLabel sort;
    // End of variables declaration//GEN-END:variables

    private void loadTableData(String sortColumn) {

    model.setRowCount(0);

    String sql =
        "SELECT medicine_id, name, category, price, quantity, expiry_date, supplier " +
        "FROM medicines " +
        "WHERE status = 'Active' " +
        "ORDER BY " + sortColumn;

    try (Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery(sql)) {

        while (rs.next()) {
            double price = rs.getDouble("price");
            int qty = rs.getInt("quantity");

            model.addRow(new Object[]{
                rs.getInt("medicine_id"),
                rs.getString("name"),
                rs.getString("category"),
                price,
                qty,
                rs.getDate("expiry_date"),
                rs.getString("supplier"),
                price * qty
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    
    private String getSortColumn() {
        return switch (combobox.getSelectedItem().toString()) {
            case "ID" -> "medicine_id";
            case "Name" -> "name";
            case "Category" -> "category";
            case "Price" -> "price";
            case "Quantity" -> "quantity";
            case "Expiry Date" -> "expiry_date";
            case "Supplier" -> "supplier";
            case "Total Value" -> "(price * quantity)";
            default -> "medicine_id";
        };
    }
    
    private void exportToCSV() {
        JFileChooser chooser = new JFileChooser();
        chooser.setSelectedFile(new java.io.File("medicine_stock.csv"));

        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            try (FileWriter fw = new FileWriter(chooser.getSelectedFile())) {

                for (int i = 0; i < model.getColumnCount(); i++) {
                    fw.write(model.getColumnName(i) + ",");
                }
                fw.write("\n");

                for (int r = 0; r < model.getRowCount(); r++) {
                    for (int c = 0; c < model.getColumnCount(); c++) {
                        fw.write(model.getValueAt(r, c).toString() + ",");
                    }
                    fw.write("\n");
                }

                JOptionPane.showMessageDialog(this, "✅ Export successful");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Export failed:\n" + e.getMessage());
            }
        }
    }
    }
